### ISSUE TITLE
New input data format

### ISSUE THREAD

**Issue by ecasellas** [meteocat/pymica#44]
Currently, data to interpolate is provided to pymica main class as a JSON file. It would be better to directly pass a Pandas DataFrame.

This change affects `pymica2.py` script and `__input_data__` function. The latter checks different aspects of input data, so the same should be done to the DataFrame. In addition, the DataFrame should be transformed into a dict as it's how pymica interpolator expects data.

**Comment by ecasellas** [comment]
@jrmiro  you sould do it in branch 44-new-input-data-format

**Comment by jrmiro** [comment]
Probably the best way to face with this will be use dictionaries instead of dataframes, as the most natural way is go to json to dictionary.
